spring.application.name=SpringSequre

spring.security.user.name=sabari
spring.security.user.password=1234

server.servlet.session.cookie.same-site=strict

spring.datasource.url =jdbc:mysql://localhost:3306/telusko
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true