spring.application.name=SpringAuth


#google Oauth2 credentials
# spring.security.oauth2.client.registration.google.client-id=874105057-9q8tgp7raiqbv749pfiqktpnq1cmgd8.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=GOCSX-uXkDADlMzl_-4FOBJ2q6PSdwGgj


#GitHub Oauth2 credentials
spring.security.oauth2.client.registration.github.client-id=Ov23libjq5CyDh45dD7s
spring.security.oauth2.client.registration.github.client-secret=1f3c7be797fc28323eecd8e349928696764b9c6d
